services:
  mememeow:
    build:
      context: .
    command: uvicorn api:app --host 0.0.0.0 --port 8275
    ports:
      - "8275:8275"
    env_file:
      - path: .env
        required: false
    volumes:
      - ./data:/app/data
    working_dir: /app
